dependencies:
- name: kafka
  version: 0.14.4
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  condition: kafka.enabled
- name: schema-registry
  version: 1.1.2
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  condition: schema-registry.enabled
